In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/social-network-ads/Social_Network_Ads.csv


In [2]:
df=pd.read_csv('/kaggle/input/social-network-ads/Social_Network_Ads.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.shape

(400, 5)

In [5]:
df.drop(columns=['User ID'], inplace=True)

In [6]:
df.shape

(400, 4)

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [8]:
df['Gender']= encoder.fit_transform(df['Gender'])

In [9]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [10]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
X

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]])

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
X=scaler.fit_transform(X)

In [15]:
X

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 3)
(80, 3)
(320,)
(80,)


In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model=Sequential()

In [20]:
model.add(Dense(1,activation='sigmoid',input_dim=X_train.shape[1]))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [23]:
model.fit(X_train,y_train,batch_size=36,epochs=100,verbose=1)

Epoch 1/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4488 - accuracy: 0.1969
Epoch 2/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4402 - accuracy: 0.1937
Epoch 3/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4313 - accuracy: 0.1937
Epoch 4/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4229 - accuracy: 0.1937
Epoch 5/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4142 - accuracy: 0.1937
Epoch 6/100
9/9 [==============================] - 0s 1ms/step - loss: 1.4058 - accuracy: 0.1969
Epoch 7/100
9/9 [==============================] - 0s 2ms/step - loss: 1.3976 - accuracy: 0.1937
Epoch 8/100
9/9 [==============================] - 0s 1ms/step - loss: 1.3889 - accuracy: 0.1969
Epoch 9/100
9/9 [==============================] - 0s 1ms/step - loss: 1.3803 - accuracy: 0.2000
Epoch 10/100
9/9 [==============================] - 0s 2ms/step - loss: 1.3724 - accuracy: 0.2031
Epoch 11/100
9/9 [===========

In [24]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 2ms/step - loss: 0.7997 - accuracy: 0.4500


[0.7996659874916077, 0.44999998807907104]

In [25]:
model.get_weights()

[array([[-0.08375267],
        [-0.37644053],
        [-0.11051611]], dtype=float32),
 array([-0.40159088], dtype=float32)]

In [26]:
#initializing my weights and bias

weights=np.ones(X_train.shape[1])
bias = 0

In [27]:
print(weights)
print(bias)

[1. 1. 1.]
0


In [28]:
def sigmoid(z):
    
    return 1/(1+np.exp(-z))

In [29]:
y_hat = sigmoid(np.dot(X_train,weights)+bias)

In [30]:
y_hat

array([0.99419942, 0.80966521, 0.06195793, 0.04254933, 0.50772553,
       0.43438522, 0.35392466, 0.99206405, 0.26363538, 0.27953048,
       0.7801569 , 0.76790752, 0.04660123, 0.2196936 , 0.53360967,
       0.22673485, 0.35950036, 0.71694322, 0.93106377, 0.91991371,
       0.21807593, 0.87608655, 0.17843602, 0.59771526, 0.26088444,
       0.81629123, 0.58273589, 0.68921113, 0.15212819, 0.20812531,
       0.07258516, 0.54658476, 0.82213278, 0.33253843, 0.46558799,
       0.8770232 , 0.82056286, 0.25915939, 0.54408541, 0.34569953,
       0.15439904, 0.98372445, 0.57288737, 0.91199521, 0.25791521,
       0.61091612, 0.76210737, 0.8693018 , 0.58005672, 0.92354789,
       0.02410567, 0.91211929, 0.14503642, 0.97730366, 0.64288517,
       0.44585634, 0.87210687, 0.66005033, 0.80313216, 0.60760494,
       0.19052336, 0.09058272, 0.6247092 , 0.85023159, 0.23730857,
       0.71147847, 0.78263844, 0.92647198, 0.88983985, 0.71524631,
       0.62311366, 0.27212168, 0.3099663 , 0.68921113, 0.90699

In [31]:
y_hat.shape

(320,)

In [32]:
#finding the loss for every point

loss = np.mean(-y_train*np.log(y_hat)- (1-y_train)*np.log(1-y_hat))

In [33]:
loss

0.5680218067917625

In [34]:
lr = 0.1 #learning rate

In [35]:
w_derivative = -(np.dot((y_train - y_hat),X_train))/X_train.shape[0] 

In [36]:
w_derivative

array([ 0.17803284, -0.10865455,  0.00730163])

In [37]:
b_derivative = -np.mean(y_train - y_hat)

In [38]:
b_derivative

0.13164203410433797

In [39]:
weights = weights-(lr*w_derivative)
bias = bias - (lr*b_derivative)

In [40]:
weights 

array([0.98219672, 1.01086546, 0.99926984])

In [41]:
bias

-0.013164203410433797

So, my weights and bias got updated. But this is done for only epoch.

In [42]:
for i in range(100):
    y_hat = sigmoid(np.dot(X_train,weights)+bias)
    w_derivative = -(np.dot((y_train - y_hat),X_train))/X_train.shape[0] 
    b_derivative = -np.mean(y_train - y_hat)
    weights = weights-(lr*w_derivative)
    bias = bias - (lr*b_derivative)
    y_hat = sigmoid(np.dot(X_train,weights)+bias)
    loss = np.mean(-y_train*np.log(y_hat)- (1-y_train)*np.log(1-y_hat))
    print("After {} epoch the loss is".format(i+1),loss)

After 1 epoch the loss is 0.5561736538245508
After 2 epoch the loss is 0.5505685226759944
After 3 epoch the loss is 0.5451658618088531
After 4 epoch the loss is 0.539958337777094
After 5 epoch the loss is 0.534938844423847
After 6 epoch the loss is 0.5301005005742361
After 7 epoch the loss is 0.5254366472029895
After 8 epoch the loss is 0.520940844142797
After 9 epoch the loss is 0.5166068663947506
After 10 epoch the loss is 0.5124287000977106
After 11 epoch the loss is 0.5084005382090696
After 12 epoch the loss is 0.5045167759451845
After 13 epoch the loss is 0.5007720060256949
After 14 epoch the loss is 0.497161013762077
After 15 epoch the loss is 0.4936787720270882
After 16 epoch the loss is 0.49032043613825776
After 17 epoch the loss is 0.4870813386852726
After 18 epoch the loss is 0.4839569843279941
After 19 epoch the loss is 0.4809430445889329
After 20 epoch the loss is 0.478035352661289
After 21 epoch the loss is 0.47522989825114587
After 22 epoch the loss is 0.4725228224700732


In [43]:
#finding the final weights and bias of ours

print(bias)
print(weights)

-0.667818517997356
[0.20514493 1.57196555 0.93943331]


**Our loss value is very close or almost equal to the the loss value in Keras. Thus our model is working fine.**